# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 02:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=100)),
                ('completed', models.BooleanField(default=False)),
                ('grade', models.CharField(max_length=10)),
                ('units', models.IntegerField(default=3)),
            ],
            options={
                'ordering': ('quarter__year', 'quarter__season', 'department', 'number'),
            },
        ),
        migrations.CreateModel(
            name='Quarter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=20)),
                ('season', models.IntegerField(choices=[(0, 'Autumn'), (1, 'Winter'), (2, 'Spring'), (3, 'Summer')], default=0)),
                ('unit_cap', models.IntegerField(default=10)),
            ],
            options={
                'ordering': ('year', 'season'),
            },
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('counting_method', models.IntegerField(choices=[(0, 'courses'), (1, 'units')], default=0)),
                ('count_required', models.IntegerField(default=1)),
                ('courses', models.ManyToManyField(to='course_planner.Course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='quarter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_planner.Quarter'),
        ),
    ]
