# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='grade',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
