# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 05:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_planner', '0003_auto_20160430_0513'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequirementSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('weight',),
            },
        ),
        migrations.AlterModelOptions(
            name='requirement',
            options={},
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='weight',
        ),
        migrations.AlterField(
            model_name='requirement',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_planner.RequirementSource'),
        ),
    ]
